import type { GameSpec } from './GameSpec';
export const examples: Record<string, GameSpec> = {
  'forest-platformer': {
    id: 'forest-platformer',
    archetype: 'platformer',
    title: 'Forest Star Rescue',
    theme: 'forest',
    player: { name: 'Ranger' },
    objective: { description: 'Collect five forest stars' },
    enemies: ['patrol-beetle'],
    collectible: 'forest-star',
    requestedMechanics: ['collectibles', 'hazards', 'patrol-enemy'],
    difficulty: 'normal',
    gameplay: { moveSpeed: 245, jumpSpeed: 440 },
    presentation: {
      backgroundColor: '#86c96f',
      hud: { healthLabel: 'Hearts', panelColor: 0x17351e },
    },
  },
  'robot-top-down': {
    id: 'robot-top-down',
    archetype: 'top-down',
    title: 'Robot Crystal Sweep',
    theme: 'robot-lab',
    player: { name: 'Utility Bot' },
    objective: { description: 'Recover six power crystals' },
    enemies: ['security-drone'],
    collectible: 'power-crystal',
    requestedMechanics: [
      'collectibles',
      'health',
      'chase-enemy',
      'projectile-shooting',
    ],
    difficulty: 'normal',
    gameplay: { moveSpeed: 235, projectileCooldown: 180 },
    presentation: {
      backgroundColor: '#102f35',
      hud: { healthLabel: 'Power', panelColor: 0x071c24 },
    },
  },
  'space-runner': {
    id: 'space-runner',
    archetype: 'runner',
    title: 'Comet Lane',
    theme: 'space',
    player: { name: 'Courier' },
    objective: { description: 'Reach the jump gate' },
    enemies: ['asteroid'],
    collectible: 'star-token',
    requestedMechanics: ['hazards', 'collectibles', 'timer'],
    difficulty: 'hard',
    gameplay: { baseSpeed: 220, maxSpeedBonus: 150, jumpSpeed: 450 },
    presentation: {
      backgroundColor: '#17134a',
      hud: { showHealth: false, scoreLabel: 'Distance' },
    },
  },
};
